language: android

android:
  components:
    - build-tools-21.1.1
    - android-21

install:
  # Check install section: http://docs.travis-ci.com/user/build-configuration/#install
  # If you'd like to skip the install stage entirely, set it to true and nothing will be run.
  - true

script:
  - ./gradlew build test
